services:
    mysql:
        image: mysql
        container_name: mysql-docker
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: reservation
            MYSQL_USER: bindisha
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - my_service_network
        volumes:
            - mysql_data:/var/lib/mysql

    springboot-app:
        image: bindisha/flightservicerepo:v2
        container_name: flightservice-container
        ports:
            - "8080:8080"
        environment:
            DB_HOST: mysql-docker
            DB_PORT: 3306
            DB_NAME: reservation
            DB_USERNAME: bindisha
            DB_PASSWORD: password
        networks:
            - my_service_network
        volumes:
            - ./app/logs:/logs
    elasticsearch:
        image: elasticsearch:8.16.1
        container_name: elasticsearch
        restart: always
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        networks:
            - my_service_network
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - es_data:/usr/share/elasticsearch/data/
    logstash:
        image: logstash:8.16.1
        container_name: logstash
        restart: always
        volumes:
            - ./logstash.conf:/logstash.conf
            - ./app/logs:/app/logs
        command: logstash -f /logstash.conf
        networks:
            - my_service_network
        depends_on:
            - elasticsearch
        ports:
            - '9600:9600'
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    kibana:
        image: kibana:8.16.1
        container_name: kibana
        restart: always
        networks:
            - my_service_network
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        volumes:
            - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
        environment:
            KIBANA_SYSTEM_PASSWORD: changeme
networks:
    my_service_network:
        external: true
volumes:
    mysql_data:
    es_data:
