services:
    mysql:
        image: mysql
        container_name: mysql-docker
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: reservation
            MYSQL_USER: bindisha
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - sping-boot-app-swarm
        volumes:
            - mysql_data:/var/lib/mysql

    springboot-app:
        image: bindisha/flightservicerepo:v2
        container_name: flightservice-container
        ports:
            - "8080:8080"
        environment:
            DB_HOST: mysql-docker
            DB_PORT: 3306
            DB_NAME: reservation
            DB_USERNAME: bindisha
            DB_PASSWORD: password
        networks:
            - sping-boot-app-swarm
        volumes:
            - ./app/logs:/logs
 networks:
    sping-boot-app-swarm:
        external: true
volumes:
    mysql_data:
